app_port = 4243

issuer = "https://api.dsavdodeka.nl"
frontend_client_id = "dodekaweb_client"
backend_client_id = "dodekabackend_client"

valid_redirects = ["http://localhost:3000/auth/callback", "https://dsavdodeka.nl/auth/callback"]

credentials_url = "http://localhost:4243/credentials/index.html"

DB_USER="dodeka"
DB_PASS="postpost"
DB_HOST="localhost"
DB_PORT=3141
DB_NAME="dodeka"
DB_NAME_ADMIN="postgres"

KV_HOST="localhost"
KV_PORT=6379
KV_PASS="redisredis"