[tool.poetry]
name = "dodekaserver"
version = "0.1.1"
description = ""
authors = ["Tip ten Brink <75669206+tiptenbrink@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
fastapi = "^0.70.0"
uvicorn = {extras = ["standard"], version = "^0.15.0"}
databases = {extras = ["postgresql"], version = "^0.5.3"}
alembic = "^1.7.5"
psycopg2-binary = "^2.9.2"
gunicorn = "^20.1.0"
pytest-asyncio = "^0.16.0"
pytest-mock = "^3.6.1"
requests = "^2.26.0"
httpx = "^0.21.1"
hiredis = "^2.0.0"
redis = "^4.0.1"
python-dotenv = "^0.19.2"
opaquepy = "^0.1.1"

[tool.poetry.scripts]
s-dodeka = "dodekaserver.main:run"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
