allowed_envs = ["envless", "localdev", "test"]

frontend_client_id = "dodekaweb_client"
valid_redirects = ["http://localhost:3000/auth/callback", "https://dsavdodeka.nl/auth/callback"]
api_root = "http://localhost:4243"
issuer = "https://api.dsavdodeka.nl"
backend_client_id = "dodekabackend_client"

credentials_url = "http://localhost:4243/credentials/"
signup_url = "https://www.av40.nl/index.php?page=Inschrijfformulier&sid=1"
onboard_email = "comcom@dsavdodeka.nl"

realm = "dodeka"