name: CI

on:
  push:
    branches:
      - ci

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CONF_REPO_PATH: 'config_source'
      IN_REPO_CONF_PATH: 'use/backend'
      CONF_TARGET: 'autosourced_config'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: 'DSAV-Dodeka/dodeka'
        token: ${{ secrets.GH_DODEKACOMCOM_TOKEN }}
        # Relative to ${{ github.workspace }}
        path: ${{ env.CONF_REPO_PATH }}
    - name: Move conf
      run: |
        mv ${{ github.workspace }}/${{ env.CONF_REPO_PATH }}/${{ env.IN_REPO_CONF_PATH }} ${{ github.workspace }}/${{ env.CONF_TARGET }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Autosource config (automated)
        file_pattern: ${{ env.CONF_TARGET }}/
