name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry==1.6.1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
    - run: |
        poetry env use python3.11
        poetry install
    - name: Install library
      run: poetry install
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ github.workspace }}/authpage/package-lock.json
    - name: Cache authpage
      id: cached-authpage
      uses: actions/cache@v2
      with:
        key: authpage-${{ hashFiles('${{ github.workspace }}/authpage') }}
        path: ${{ github.workspace }}/src/apiserver/resources/static/credentials
    - name: Build credentials
      run: |
        npm install
        npm run build
      working-directory: ${{ github.workspace }}/authpage
    - name: Pytest
      run: poetry run pytest
    - name: Black
      run: poetry run black src tests
    - name: Ruff
      run: poetry run ruff src tests
