name: CI

on:
  push:
    branches:
      - ci-test

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      FOO: ${{ secrets.SAMPLE_SECRET }}
      BAR: ${{ secrets.SAMPLE_SECRET_TWO }}
    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: "dodeka.tipten.nl"
        username: "dodekatest"
        key: ${{ secrets.SSH_PRIVATE_KEY_DODEKATEST }}
        port: ${{ secrets.SSH_DODEKATEST_PORT }}
        envs: FOO,BAR
        script: |
          echo "I am $FOO"
          echo "I am $BAR"
        
